Added missing buffinfos
xoxfaby/BetterUI pull request #111
Opened 2022-04-10 10:36 UTC by DestroyedClone

Added the missing `DLC1Content` buffs, `JunkContent` Buffs, and the 2 new `RoR2Content` Buffs (`VoidFogMild`, `VoidFogStrong`) for BuffInfos

2022-04-10 10:38 UTC, DestroyedClone commented
I have read the CLA Document and I hereby sign the CLA

2022-10-08 09:48 UTC, xoxfaby requested changes
As per our discord conversation, I'd like to know if you're willing to check all the existing and new buff descriptions for stylistic and formatting consistency.

2022-11-06 23:50 UTC, xoxfaby commented
I'm going to merge this as is since it's better than not adding them at all, but if you ever wanna tackle my suggestion, feel free to.

2022-11-06 23:51 UTC, xoxfaby approved these changes

2022-11-06 23:52 UTC, merged