Raincoat rework fix
xoxfaby/BetterUI pull request #164
Opened 2023-02-14 02:20 UTC by Damglador

2023-02-14 02:22 UTC, Damglador commented
I have read the CLA Document and I hereby sign the CLA

2023-02-14 15:31 UTC, xoxfaby requested changes
Could you include English strings as well?

2023-02-15 06:23 UTC, Damglador commented
> Could you include English strings as well?

Ok

2023-02-15 10:51 UTC, Damglador commented
Im done

2023-05-31 21:25 UTC, xoxfaby requested changes

2023-05-31 21:25 UTC, xoxfaby commented on ModComponents/ItemStats.cs
> +            RegisterStat(DLC1Content.Items.ImmuneToDebuff, "BETTERUI_RAINCOAT", 1f, stackingFormula: LinearStacking, statFormatter: StatFormatter.Charges);
This should probably use the Raincoat item name, not a custom betterui string, see other items as example

2023-05-31 21:28 UTC, xoxfaby commented on ModComponents/ItemStats.cs
> +            RegisterStat(DLC1Content.Items.ImmuneToDebuff, "BETTERUI_RAINCOAT", 1f, stackingFormula: LinearStacking, statFormatter: StatFormatter.Charges);
Actually it should probably say "Debuffs Blocked" ?

2023-05-31 21:28 UTC, xoxfaby commented on ModComponents/ItemStats.cs
> +            RegisterStat(DLC1Content.Items.ImmuneToDebuff, "BETTERUI_RAINCOAT", 1f, stackingFormula: LinearStacking, statFormatter: StatFormatter.Charges);
and use a new StatFormatter for Debuffs? Charges also kinda makes sense

2023-06-23 04:27 UTC, merged