added arbitrary item sorting
xoxfaby/BetterUI pull request #178
Opened 2023-10-08 23:12 UTC by K-91

2023-10-08 23:13 UTC, K-91 commented
I have read the CLA Document and I hereby sign the CLA

2023-10-08 23:48 UTC, xoxfaby requested changes
:)

2023-10-08 23:48 UTC, xoxfaby commented on ModComponents/ItemSorting.cs
> +            StringBuilder parsedName = new StringBuilder();
don't create a string builder every time, use the BetterUI shared stringbuilder

2023-10-08 23:48 UTC, xoxfaby commented on ModComponents/ItemSorting.cs
> +        private static IOrderedEnumerable<ItemIndex> filteredSort<T>(IOrderedEnumerable<ItemIndex> list, Inventory inventory, ItemSorter<T> sorter, ItemFilter filter = null, bool reversed = false, It
lol

2023-10-09 05:12 UTC, xoxfaby approved these changes

2023-10-09 05:13 UTC, merged