Weakpoint Combo StatDisplay, Config Description for StatDisplay from regexmap
xoxfaby/BetterUI pull request #70
Opened 2022-03-02 22:55 UTC by Bubbet

2022-03-02 22:56 UTC, Bubbet commented
I have read the CLA Document and I hereby sign the CLA

2022-03-03 05:01 UTC, xoxfaby requested changes

2022-03-03 05:01 UTC, xoxfaby commented on ModComponents/StatsDisplay.cs
> +                EntityStates.Railgunner.Weapon.BaseFireSnipe.onWeakPointHit += WeakPointComboHit;
These are never removed? Should add a listener to onDisable to remove these.

2022-03-03 05:01 UTC, xoxfaby commented on ModComponents/StatsDisplay.cs
> +                EntityStates.Railgunner.Weapon.BaseFireSnipe.onWeakPointHit += WeakPointComboHit;
Also, does this work on clients or only on the host?

2022-03-03 05:05 UTC, Bubbet commented on ModComponents/StatsDisplay.cs
> +                EntityStates.Railgunner.Weapon.BaseFireSnipe.onWeakPointHit += WeakPointComboHit;
The event is fired in an entity state, i assume it works for everyone. Which i realized after committing means other railgun players.

2022-03-03 05:06 UTC, xoxfaby commented on ModComponents/StatsDisplay.cs
> +                EntityStates.Railgunner.Weapon.BaseFireSnipe.onWeakPointHit += WeakPointComboHit;
Definitely need to test how this works in multiplayer

2022-03-03 05:07 UTC, xoxfaby commented on BetterUI.csproj
> +    <PackageReference Include="KinematicCharacterController" Version="1.0.0" />
Are there any other DLLs we should be adding? Anything that's not part of Unity or anything else

2022-03-03 05:10 UTC, Bubbet commented on ModComponents/StatsDisplay.cs
> +                EntityStates.Railgunner.Weapon.BaseFireSnipe.onWeakPointHit += WeakPointComboHit;
Best part about that is the missed event does not give any information as to who missed the shot.

2022-03-03 05:26 UTC, Bubbet commented on ConfigManager.cs
> +                "Valid Parameters:\n" + string.Join(" ", StatsDisplay.regexmap.Keys));
![image](https://user-images.githubusercontent.com/16075375/156501908-61cf07d5-cabf-4b2f-9a78-035265260794.png)
![image](https://user-images.githubusercontent.com/16075375/156501959-3bdb0fa8-2439-46cd-85ee-1dcd9e9e87e1.png)

2022-03-06 04:44 UTC, Bubbet commented
Most recent commit is how i fixed #71

2022-03-10 18:52 UTC, xoxfaby requested changes

2022-03-10 18:52 UTC, xoxfaby commented on ModComponents/StatsDisplay.cs
> +                { "$velocity", (statBody) => (statBody.characterMotor as IPhysMotor).velocity.magnitude.ToString("0.##") },
Add null check in case statBody doesn't have a characterMotor

2022-03-10 18:52 UTC, xoxfaby commented on ModComponents/StatsDisplay.cs
> +                        var vector = (statBody.characterMotor as IPhysMotor).velocity;
same as above

2022-03-10 18:52 UTC, xoxfaby commented on ModComponents/StatsDisplay.cs
> +            sorted.Sort((s, s1) => Math.Sign(s1.Length - s.Length));
Math.Sign call here is not needed.

2022-03-10 18:52 UTC, xoxfaby commented on ModComponents/StatsDisplay.cs
> +            if (normalText.Contains("$weakpointcombo"))
This needs to be move to onEnable if we are gonna unhook in onDisable, otherwise move it to onDestroy

2022-03-10 18:52 UTC, xoxfaby commented on ModComponents/StatsDisplay.cs
> +        static void onDisable()
see comment about moving this to onDestroy

2022-03-12 04:19 UTC, closed without merging